"""Manage the code_graph_search Java process lifecycle.

Handles building, starting, indexing, and stopping the code_graph_search
server. Branch-aware: generates config pointing at the checked-out PR
branch so the index reflects the exact code under review.
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import tempfile
import time
from pathlib import Path

from review_tool.config import GraphConfig
from review_tool.graph_client import GraphClient

log = logging.getLogger(__name__)


# ── Build ────────────────────────────────────────────────────────────────────


def find_jar(cgs_dir: str) -> Path | None:
    """Find the code_graph_search JAR in the project directory."""
    jar = Path(cgs_dir) / "app" / "target" / "code-graph-search.jar"
    if jar.exists():
        return jar
    return None


def build_jar(cgs_dir: str, timeout: int = 300) -> Path:
    """Build code_graph_search from source using Maven.

    Returns the path to the built JAR.
    """
    cgs_path = Path(cgs_dir)
    build_script = cgs_path / "build.sh"

    if build_script.exists():
        log.info("Building code_graph_search via build.sh in %s", cgs_dir)
        cmd = ["bash", str(build_script)]
    else:
        log.info("Building code_graph_search via mvn package in %s", cgs_dir)
        cmd = ["mvn", "package", "-DskipTests"]

    result = subprocess.run(
        cmd,
        cwd=str(cgs_path),
        capture_output=True,
        text=True,
        timeout=timeout,
    )

    if result.returncode != 0:
        log.error("Build failed:\nstdout: %s\nstderr: %s", result.stdout[-500:], result.stderr[-500:])
        raise RuntimeError(f"code_graph_search build failed (exit {result.returncode})")

    jar = find_jar(cgs_dir)
    if not jar:
        raise FileNotFoundError(f"JAR not found after build in {cgs_dir}")

    log.info("Built JAR: %s", jar)
    return jar


def ensure_jar(cgs_dir: str) -> Path:
    """Find existing JAR or build from source."""
    jar = find_jar(cgs_dir)
    if jar:
        log.info("Found existing JAR: %s", jar)
        return jar

    log.info("JAR not found, building from source...")
    return build_jar(cgs_dir)


# ── Config generation ────────────────────────────────────────────────────────


def generate_graph_config(
    repo_path: str,
    repo_id: str = "review_target",
    repo_name: str = "review_target",
    branch: str = "",
    data_dir: str | None = None,
    port: int = 8080,
) -> Path:
    """Generate a config.yaml for code_graph_search.

    Args:
        repo_path: Absolute path to the checked-out repository (on the PR branch).
        repo_id: Unique ID for this repo in the graph.
        repo_name: Display name for the repo.
        branch: The branch that is checked out (for logging/identification).
        data_dir: Where to store graph data. Defaults to a temp directory.
        port: HTTP port for the REST server.
    """
    if data_dir is None:
        data_dir = tempfile.mkdtemp(prefix="cgs_data_")

    config_content = f"""\
# Auto-generated by review-tool for PR review
# Repo: {repo_name}
# Branch: {branch or '(default)'}
# Path: {repo_path}

storage:
  dataDir: "{data_dir}"

repositories:
  - id: "{repo_id}"
    name: "{repo_name}"
    path: "{repo_path}"
    languages:
      - JAVA
      - GO
      - RUST
      - TYPESCRIPT
      - JAVASCRIPT
      - C
      - CPP
      - PYTHON

server:
  port: {port}
"""
    config_path = Path(tempfile.mktemp(prefix="cgs_config_", suffix=".yaml"))
    config_path.write_text(config_content)
    log.info(
        "Generated code_graph_search config: %s (repo=%s, branch=%s, path=%s, port=%d)",
        config_path,
        repo_id,
        branch or "(default)",
        repo_path,
        port,
    )
    return config_path


# ── Server lifecycle ──────────────────────────────────��──────────────────────


def start_graph_server(
    jar_path: str | Path,
    config_path: str | Path,
    log_file: str | None = None,
) -> subprocess.Popen:
    """Start code_graph_search as a subprocess.

    Args:
        jar_path: Path to code-graph-search.jar.
        config_path: Path to the config YAML.
        log_file: Optional file to redirect server output to.

    Returns:
        The subprocess.Popen handle.
    """
    jar = Path(jar_path)
    if not jar.exists():
        raise FileNotFoundError(f"code_graph_search JAR not found: {jar}")

    cmd = [
        "java",
        "--enable-preview",
        "-jar",
        str(jar),
        "--config",
        str(config_path),
    ]

    log.info("Starting code_graph_search: %s", " ".join(cmd))

    if log_file:
        log.info("Server output → %s", log_file)
        log_fh = open(log_file, "w")
        process = subprocess.Popen(cmd, stdout=log_fh, stderr=subprocess.STDOUT)
    else:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )

    log.info("code_graph_search started (pid=%d)", process.pid)
    return process


def wait_for_ready(
    host: str = "http://localhost:8080",
    timeout: int = 120,
) -> bool:
    """Poll the health endpoint until the server is ready or timeout."""
    client = GraphClient(base_url=host, timeout=5.0)
    deadline = time.monotonic() + timeout
    attempt = 0

    while time.monotonic() < deadline:
        attempt += 1
        if client.healthy():
            log.info("code_graph_search is ready at %s (after %d attempts)", host, attempt)
            client.close()
            return True
        if attempt % 5 == 0:
            log.info("  Still waiting for code_graph_search... (attempt %d)", attempt)
        time.sleep(2)

    client.close()
    log.error("code_graph_search did not become ready within %ds (%d attempts)", timeout, attempt)
    return False


def wait_for_indexing(
    client: GraphClient,
    repo_id: str,
    timeout: int = 120,
    poll_interval: float = 3.0,
) -> bool:
    """Poll until the repo is indexed by checking element counts.

    Since code_graph_search doesn't have a dedicated status endpoint,
    we poll search results until we get non-empty results or timeout.
    """
    deadline = time.monotonic() + timeout
    attempt = 0
    last_count = 0

    log.info("Waiting for indexing of repo %s (timeout=%ds)...", repo_id, timeout)

    while time.monotonic() < deadline:
        attempt += 1
        try:
            results = client.search("*", repo_id=repo_id, limit=1)
            count = len(results)

            if count > 0:
                # Do a second check after a brief pause to ensure indexing is stable
                time.sleep(2)
                results2 = client.search("*", repo_id=repo_id, limit=5)
                count2 = len(results2)
                log.info(
                    "Indexing appears complete for %s: %d elements found (poll %d)",
                    repo_id,
                    count2,
                    attempt,
                )
                return True

            if attempt % 3 == 0:
                log.info("  Indexing in progress for %s... (poll %d, count=%d)", repo_id, attempt, count)

        except Exception:
            if attempt % 5 == 0:
                log.debug("  Index poll failed (attempt %d)", attempt, exc_info=True)

        time.sleep(poll_interval)

    log.warning("Indexing did not complete within %ds for repo %s", timeout, repo_id)
    return False


def stop_graph_server(process: subprocess.Popen, timeout: int = 10) -> None:
    """Gracefully stop the code_graph_search process."""
    if process.poll() is not None:
        log.info("code_graph_search already stopped (exit=%d)", process.returncode)
        return

    log.info("Stopping code_graph_search (pid=%d)...", process.pid)
    process.send_signal(signal.SIGTERM)
    try:
        process.wait(timeout=timeout)
        log.info("code_graph_search stopped gracefully")
    except subprocess.TimeoutExpired:
        log.warning("code_graph_search did not stop gracefully, sending SIGKILL")
        process.kill()
        process.wait(timeout=5)
        log.info("code_graph_search killed")


# ── MCP config ───────────────────────────────────────────────────────────────


def generate_mcp_config(jar_path: str, config_path: str) -> Path:
    """Generate an MCP config JSON for passing to claude --mcp-config."""
    mcp_cfg = {
        "mcpServers": {
            "code_graph": {
                "command": "java",
                "args": [
                    "--enable-preview",
                    "-jar",
                    jar_path,
                    "--mcp-stdio",
                    "--config",
                    config_path,
                ],
            }
        }
    }

    path = Path(tempfile.mktemp(prefix="mcp_config_", suffix=".json"))
    path.write_text(json.dumps(mcp_cfg, indent=2))
    log.info("Generated MCP config: %s", path)
    return path
